// Generated by Wrangler on Mon Apr 15 2024 15:18:13 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	CLOUDFLARE_TURNSTILE_SECRET: string;
	CLOUDFLARE_TURNSTILE_SITEKEY: string;
	POSTMARK_API_TOKEN: string;
	POSTMARK_DEFAULT_FROM: string;
	DB: D1Database;
}
