// Generated by Wrangler on Tue Apr 09 2024 14:36:26 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	POSTMARK_API_TOKEN: "string";
	POSTMARK_DEFAULT_FROM: "string";
	DB: D1Database;
}
